// JSON -  Javascript object notaion
// Json can be in {} or [] format.
// Json is an object but with some restrictions. It is used to exchange data between client and server.
// It is a string format that can be easily parsed and generated by JavaScript.
// it only take 2 values -  Key and value Pair
// Key -  take only in string Format (" ")
// value -  can be in string, number, boolean, null, array and object format. It cannot take function and expression as value .
